services:

  postgres:
    image: postgres:16-alpine
    container_name: joyeria-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - joyeria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./inventario
      dockerfile: Dockerfile
    container_name: joyeria-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO}
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - joyeria-network
    restart: unless-stopped

  frontend:
    build:
      context: ./joyeria-frontend
      dockerfile: Dockerfile
    container_name: joyeria-frontend
    ports:
    - "80:80"
    - "${FRONTEND_PORT}:443"
    depends_on:
      - backend
    networks:
      - joyeria-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  joyeria-network:
    driver: bridge